### ISSUE TITLE
Definition of habitat benchmarks in the beginning of loop3

### ISSUE THREAD

**Issue by catarinawor** [Pacific-salmon-assess/samSim#19]
It seems that the first step at the start of loop 3 is to define the management benchmarks for the projections, [starting here](https://github.com/Pacific-salmon-assess/samSim/blob/cc95a11fc12501362de496430c340b0f2acde120/R/genericRecoverySimulator.R#L1259). However, only the benchmarks related to `bm == "stockRecruit"` are defined here. Is it because these are the only benchmarks that would depend on the recruitment parameters?

**Comment by CamFreshwater** [comment]
Again if memory serves I believe that's correct. It was easier (if perhaps less clear) to just calculate the other abundance based BMs as spawner abundances were generated/observed.

**Comment by carrieholt** [comment]
Habitat-based benchmark are essentially the same as SR-based benchmarks, they are just based on Ricker inputs that are generated from a habitat-based model (e.g., from watershed-area model for Chinook salmon)
