### ISSUE TITLE
adjustment for sigma autocorrelation

### ISSUE THREAD

**Issue by catarinawor** [Pacific-salmon-assess/samSim#26]
I noticed that an adjustment for sigmaR is proposed  to account for temporal autocorrelation [here](https://github.com/Pacific-salmon-assess/samSim/blob/03892454b30039460dc5a510fb8227cf1b83a4e2/R/genericRecoverySimulator.R#L549)
 I am not super sure, but I think we might be missing a sqrt?
i.e. shouldn't it be:

ricSig <- sqrt(ricSig^2 * (1 - rho^2))

?

**Comment by carrieholt** [comment]
Yes, you're right. However, I don't think any of us have used this code because our models have not included an AR(1) process. But, yes, I think it would be good to correct that. Thanks.

**Comment by catarinawor** [comment]
You are right! None of the study cases uses this adjustment. I just pushed my suggested change to the LRP branch.
