### ISSUE TITLE
Add safeguard to prevent adding 3 beta errors to catch? 

### ISSUE THREAD

**Issue by catarinawor** [Pacific-salmon-assess/samSim#27]
Given the email discussions on the layers of Beta() error on ER, and how it varies between the master and LRP branches, I am wondering if it would be a good idea to add a few lines setting
the variables `mixOUSig` and `singOUSig` to zero if `harvContRule == "fixedER"`. This would guarantee that we never have the three layers of Beta uncertainty applied by accident.  

this change would be implemented [here](https://github.com/Pacific-salmon-assess/samSim/blob/9516d8f5efe12235b565038d6c5970f99aa41d72/R/genericRecoverySimulator.R#L1568) 

Let me know what you think -- no rush.

**Comment by carrieholt** [comment]
Sounds great. Thanks!

**Comment by catarinawor** [comment]
Done!
