### ISSUE TITLE
arSigTransform correction

### ISSUE THREAD

**Issue by catarinawor** [Pacific-salmon-assess/samSim#29]
I am wondering if the arSigTransform option should be adjusted. see [here](https://github.com/Pacific-salmon-assess/samSim/blob/329723f14324a21b061cba59e235acf4331d0c8f/R/genericRecoverySimulator.R#L520)

I think that the adjustment should be:
```
ricSig <- ricSig * sqrt(1 - rho^2)
```
and not:
```
ricSig <- ricSig^2 * (1 - rho^2)

```
The adjustment is also done twice, in [line 520](https://github.com/Pacific-salmon-assess/samSim/blob/329723f14324a21b061cba59e235acf4331d0c8f/R/genericRecoverySimulator.R#L520) and in [line 548](https://github.com/Pacific-salmon-assess/samSim/blob/329723f14324a21b061cba59e235acf4331d0c8f/R/genericRecoverySimulator.R#L548)

I think we should remove one of these. 

Let me know what you think!

**Comment by carrieholt** [comment]
Yes, I agree. I don't think we used AR(1) version of the Ricker in our work with Cam (Fraser or Nass), so I don't think those lines were ever implemented. It looks like ricSig was mislabeled when it was supposed to be ricVar in that context (coding likely changed, and that line should have been updated). Yes, to removing one. If ricSig does not change among trials (which I don't think it does...), then can omit the second.

**Comment by carrieholt** [comment]
I can go ahead and do it, unless you're already in the code changing other things?

**Comment by catarinawor** [comment]
I just pushed the fix described above. I realized that the second instance of the code is only used when the parameter values are pulled from a posterior distribution and therefore change in every trial, as @carrieholt pointed out. So I left both instances.
